package gui.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
*
* This class was automatically generated by the
* entirej plugin from the form.  It
* should not be modified by hand.
 */
public class F_APP_GUI {
	public static final String ID = "AppGUI";

}